task:
  container:
    image: $ELECTRUM_IMAGE
    cpu: 1
    memory: 2G
  matrix:
    - name: "unittests: Tox Python $ELECTRUM_PYTHON_VERSION"
      env:
        ELECTRUM_IMAGE: python:$ELECTRUM_PYTHON_VERSION
        TOXENV: py3
        ELECTRUM_PYTHON_NAME: python3
      matrix:
       - env:
           ELECTRUM_PYTHON_VERSION: 3.8
       - name: "unittests: Tox Python 3 debug mode"
         env:
           ELECTRUM_PYTHON_VERSION: 3
           # enable additional checks:
           PYTHONASYNCIODEBUG: "1"
           PYTHONDEVMODE: "1"
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $ELECTRUM_IMAGE && cat $ELECTRUM_REQUIREMENTS_CI && cat $ELECTRUM_REQUIREMENTS
  version_script:
    - $ELECTRUM_PYTHON_NAME --version
  tag_script:
    - git tag
  install_script:
    - apt-get update
    - apt-get -y install libsecp256k1-dev
    - pip install -r $ELECTRUM_REQUIREMENTS_CI
  tox_script:
    - export PYTHONASYNCIODEBUG
    - export PYTHONDEVMODE
    - tox
  coveralls_script:
    - if [ ! -z "$COVERALLS_REPO_TOKEN" ] ; then coveralls ; fi
  env:
    ELECTRUM_REQUIREMENTS_CI: contrib/requirements/requirements-ci.txt
    ELECTRUM_REQUIREMENTS: contrib/requirements/requirements.txt
    # following CI_* env vars are set up for coveralls
    CI_NAME: "CirrusCI"
    CI_BUILD_NUMBER: $CIRRUS_BUILD_ID
    CI_JOB_ID: $CIRRUS_TASK_ID
    CI_BUILD_URL: "https://cirrus-ci.com/task/$CIRRUS_TASK_ID"
    CI_BRANCH: $CIRRUS_BRANCH
    CI_PULL_REQUEST: $CIRRUS_PR
    # in addition, COVERALLS_REPO_TOKEN is set as an "override" in https://cirrus-ci.com/settings/...
  depends_on:
    - "linter: Flake8 Mandatory"
task:
    name: "build: Windows"
    container:
      dockerfile: contrib/build-wine/Dockerfile
      cpu: 1
      memory: 2G
    pip_cache:
      folder: contrib/build-wine/.cache/win32/wine_pip_cache
      fingerprint_script:
        - echo $CIRRUS_TASK_NAME
        - git ls-files -s contrib/deterministic-build/*.txt
        - git ls-files -s contrib/build-wine/
    build2_cache:
      folder: contrib/build-wine/.cache/win32/build
      fingerprint_script:
        - echo $CIRRUS_TASK_NAME
        - cat contrib/make_libsecp256k1.sh | sha256sum
        - cat contrib/make_libusb.sh | sha256sum
        - cat contrib/make_zbar.sh | sha256sum
        - git ls-files -s contrib/build-wine/
    build_script:
      - cd contrib/build-wine
      - ./make_win.sh
    binaries_artifacts:
      path: "contrib/build-wine/dist/*"
    env:
      CIRRUS_WORKING_DIR: /opt/wine64/drive_c/electrum
      CIRRUS_DOCKER_CONTEXT: contrib/build-wine
    depends_on:
      - "unittests: Tox Python 3.8"
task:
    name: "Run Windows Regression Tests"
    compute_engine_instance:
      image_project: cirrus-images
      image: family/docker-builder
      platform: linux
      cpu: 1
      memory: 1G
    pip_cache:
      folder: ~/.cache/pip
      fingerprint_script: echo Regtest && echo docker_builder && cat $ELECTRUM_REQUIREMENTS
    install_script:
      - apt-get update
      - apt-get -y install libsecp256k1-dev curl jq bc
      - pip3 install .[tests]
      - "BITCOIND_VERSION=$(curl https://bitcoincore.org/en/download/ | grep -E -i --only-matching 'Latest version: [0-9\\.]+' | grep -E --only-matching '[0-9\\.]+')"
      - BITCOIND_FILENAME=bitcoin-$BITCOIND_VERSION-x86_64-linux-gnu.tar.gz
      - BITCOIND_PATH=/tmp/bitcoind/$BITCOIND_FILENAME
      - BITCOIND_URL=https://bitcoincore.org/bin/bitcoin-core-$BITCOIND_VERSION/$BITCOIND_FILENAME
      - tar -xaf $BITCOIND_PATH || (rm -f /tmp/bitcoind/* && curl --output $BITCOIND_PATH $BITCOIND_URL && tar -xaf $BITCOIND_PATH)
      - cp -a bitcoin-$BITCOIND_VERSION/* /usr/
    bitcoind_service_background_script:
      - electrum/tests/regtest/run_bitcoind.sh
    electrumx_service_background_script:
      - electrum/tests/regtest/run_electrumx.sh
    regtest_script:
      - sleep 10s
      - python3 -m unittest electrum/tests/regtest.py
    env:
      ELECTRUM_REQUIREMENTS: contrib/requirements/requirements.txt
      # ElectrumX exits with an error without this:
      ALLOW_ROOT: 1
    depends_on:
      - "linter: Flake8 Mandatory"
