task:
  name: Windows Build and Regtest
  container:
    dockerfile: contrib/build-wine/Dockerfile
    cpu: 1
    memory: 2G
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo Regtest && echo docker_builder && cat $ELECTRUM_REQUIREMENTS
    populate_script: mkdir -p ~/.cache/pip
  electrum_cache:
    folder: /tmp/electrum-build
    populate_script: mkdir -p /tmp/electrum-build
  bitcoind_cache:
    folder: /tmp/bitcoind
    populate_script: mkdir -p /tmp/bitcoind
  build_script:
    - cd contrib/build-wine
    - ./make_win.sh
  binaries_artifacts:
    path: "contrib/build-wine/dist/*"
  install_script:
    - apt-get update
    - apt-get -y install libsecp256k1-dev curl jq bc
    - pip3 install .[tests]
    # install e-x some commits after 1.16.0 tag
    - pip3 install git+https://github.com/spesmilo/electrumx.git@4e66804dc0d668cd6bd4602b547e2f5b2e227e97
    - "BITCOIND_VERSION=$(curl https://bitcoincore.org/en/download/ | grep -E -i --only-matching 'Latest version: [0-9\\.]+' | grep -E --only-matching '[0-9\\.]+')"
    - BITCOIND_FILENAME=bitcoin-$BITCOIND_VERSION-x86_64-linux-gnu.tar.gz
    - BITCOIND_PATH=/tmp/bitcoind/$BITCOIND_FILENAME
    - BITCOIND_URL=https://bitcoincore.org/bin/bitcoin-core-$BITCOIND_VERSION/$BITCOIND_FILENAME
    - tar -xaf $BITCOIND_PATH || (rm -f /tmp/bitcoind/* && curl --output $BITCOIND_PATH $BITCOIND_URL && tar -xaf $BITCOIND_PATH)
    - cp -a bitcoin-$BITCOIND_VERSION/* /usr/
  bitcoind_service_background_script:
    - electrum_nmc/electrum/tests/regtest/run_bitcoind.sh
  electrumx_service_background_script:
    - electrum_nmc/electrum/tests/regtest/run_electrumx.sh
  regtest_script:
    - sleep 10s
    - apt-get update
    - apt-get -y install libsecp256k1-0 python3-pip python3-cryptography sudo python3-setuptools
    - cd /opt/wine64/drive_c/electrum-nmc
    - python3 -m pip install --user -e .
    - python3 -m unittest /opt/wine64/drive_c/electrum-nmc/electrum_nmc/electrum/tests/regtest2.py  # Run the regtest2.py script
  env:
    CIRRUS_WORKING_DIR: /opt/wine64/drive_c/electrum-nmc
    ALLOW_ROOT: 1
    ELECTRUM_REQUIREMENTS: contrib/requirements/requirements-travis.txt
    WINEDEBUG: fixme-all

